### PR TITLE
BREAKING CHANGE: hopefully fix semantic-release

### PR DESCRIPTION
**Pull request by jamen**
@ColinEberhardt My bad, I had a bit of fumbling with semantic-release.  Forgot to follow the commit formatting, tried to fix it but that failed, so this is my next attempt.  From what I understand you need to PR to create a release.

Edit: I _could_ create a branch from current master, rebase master so its back to semantic-release only commits then `git push --force`.  Then fix the commits I made and try another PR.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
> My bad, I had a bit of fumbling with semantic-release. 

No worries! 

> From what I understand you need to PR to create a release.

No, you don't need a PR to create a release. Semantic release is run on every commit to master after a successful build:

https://github.com/rollup/rollup-plugin-wasm/blob/master/.travis.yml#L13

typically this would be as a result of a merge commit from a PR, but doesn't have to be. You could just push to master.

A breaking change, that bumps the major version number needs a `BREAKING CHANGE` in the commit message footer, as described here:

https://gist.github.com/stephenparish/9941e89d80e2bc58a153#breaking-changes

I'd recommend doing a simple no-op style commit, with a breaking change message, create a PR then merging to master.

**Comment by ColinEberhardt** [comment]
Your commit message formatting isn't quite right. Your message was:

```
BREAKING CHANGE: simplify wasm imports

(See last 2 commits.  This triggers semantic-release because I messed up)
```

The correct message format is:

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

So for this commit, it would look something like:

```
feat: simplify wasm imports

BREAKING CHANGE: wasm imports have been simplified, to migrate to the new version you must do ...
```

**Comment by jamen** [comment]
@ColinEberhardt Aha!  Thanks for the help.  I think I got it this time.

**Comment by ColinEberhardt** [comment]
That worked :-)

https://github.com/rollup/rollup-plugin-wasm/releases/tag/v3.0.0

And good job with the decent documentation on the breaking change 👍

**Pull request merged**
